#include <stdint.h>
#include <eosiolib/capi/eosio/action.h>
#include <eosiolib/capi/eosio/crypto.h>
#include <eosiolib/capi/eosio/permission.h>
#include <eosiolib/capi/eosio/privileged.h>
#include <eosiolib/capi/eosio/transaction.h>
#include <eosiolib/capi/eosio/chain.h>
#include <eosiolib/capi/eosio/db.h>
#include <eosiolib/capi/eosio/print.h>
#include <eosiolib/capi/eosio/system.h>
#include <eosiolib/capi/eosio/types.h>
