[package]
name = "hello"
version = "0.1.0"
authors = ["Leo Ribeiro <leordev@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
eosio_cdt = { path = "../../eosio_cdt" }
bytes = "0.5.3"
serde = { version = "1.0.63", features = ["derive"] }
